version: "3.4"
services:
  app:
    image: diazharizky/golang:1.17.5-alpine
    volumes:
      - ../../:${PWD}/../..
      - go_dep:/go
    working_dir: ${PWD}/../..
    entrypoint: /bin/sh
    command: -c "tail -f /dev/null"
    ports:
      - 3000:8080
