version: "3.4"
services:
  redis:
    image: redis:6.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  build_dep:
    image: diazharizky/golang:1.17.5-alpine
    volumes:
      - ../../:${PWD}/../..
      - go_dep:/go
    working_dir: ${PWD}/../..
    command: go mod download

  test:
    image: diazharizky/golang:1.17.5-alpine
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - CONFIG_FILE_PATH=${PWD}/../../configs
      - CACHE_HOST=redis
      - CACHE_PORT=6379
    volumes:
      - ../../:${PWD}/../..
      - go_dep:/go
    working_dir: ${PWD}/../..
    command: make test

  app:
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - CACHE_HOST=redis
      - CACHE_PORT=6379

volumes:
  go_dep: null
